# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435')),
                ('slug', models.CharField(max_length=20, unique=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430 \u0432 URL')),
                ('name', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432 \u0441\u0442\u0440\u043e\u043a\u0435 \u043c\u0435\u043d\u044e')),
            ],
        ),
        migrations.AlterField(
            model_name='callback',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0435\u0440\u0435\u0437\u0432\u043e\u043d\u0438\u043b\u0438?'),
        ),
    ]
